### PR TITLE
Fix typo in shutdown message

### PR DESCRIPTION
**Pull request by diogosalazar**
Small typo there.
I also think the way the message reads is a bit weird right now.

### CODE REVIEW

**Comment by jimmyca15** [comment]
@diogosalazar 

You're right the wording is weird here. I think rather than just fixing the typo, we should revisit the message.

**Comment by jimmyca15** [comment]
@mcy94w 

The sentence should be something along the lines of 
"Terminating the process _because_ the CTRL signal was received."
or
"CTRL signal received. The process will now terminate."

**Comment by jamestelfer** [comment]
This message with the typo is shipping in the ASP.NET container. Can I help somehow get this minor change modified further and through review? It seems rude to just raise a different pull request.

**Comment by shirhatti** [comment]
@diogosalazar Do you mind updating your PR with the phrasing Jimmy suggested? If not, do you mind I push directly to your branch with the updated text

**Comment by shirhatti** [comment]
Thanks @diogosalazar!

**Pull request merged**
