### PR TITLE
Handle environment variables with single or double quotes

### PR DESCRIPTION
**Pull request by jdebbink**
Fixes https://github.com/Microsoft/IIS.ServiceMonitor/issues/40

Entity Framework connection strings use single quotes so this was how the issue was discovered.

### CODE REVIEW

**Comment by shirhatti** [comment]
Based on offline conversation with @mcy94w, this fix didn't work. @mcy94w will add repro steps in here

**Comment by jdebbink** [comment]
@mcy94w anything you can share? We have a fork of this and are in production with these changes. We'd rather not continue to maintain a fork.

**Comment by jdebbink** [comment]
@shirhatti @mcy94w

**Comment by shirhatti** [comment]
ping @mcy94w

**Comment by wealthify-dev** [comment]
@mcy94w it'd be great to push this forward or understand what's holding it back. Are you able to help?

**Comment by bariscaglar** [comment]
@jhkimnew to comment

**Comment by jhkimnew** [comment]
@mcy94w left the team long time ago and I don't have any context on this issue.
I will investigate this instead of @mcy94w .  
@shirhatti Would you let me know why this PR was not approved?

**Comment by shirhatti** [comment]
Sorry @jhkimnew! It's been long enough that I don't remember what the issue was

**Comment by jhkimnew** [comment]
Oh, I just realize what @mcy94w wanted to say. He suggested to update to handle the environment name as well as the environment value.

For example, the below two environment variabes should be handled.

set 'SINGLE'='quote'
set "DOUBLE"="quote"

**Comment by jhkimnew** [comment]
I have created a new PR to fix the issue.
https://github.com/microsoft/IIS.ServiceMonitor/pull/64

So, I am closing this PR, which is not maintained anymore.

**Pull request closed without merging**
